pipeline {
    agent {
        docker {
            image 'node:14-alpine'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building based off the alpine image'
                sh '''
                ls
                pwd
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing alpine image'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying image'
            }
        }
    }
}